export const ENTITY_FETCH_ABANDON = 'ENTITY_FETCH_ABANDON';
export const ENTITY_FETCH_FAILURE = 'ENTITY_FETCH_FAILURE';
export const ENTITY_FETCH_REQUEST = 'ENTITY_FETCH_REQUEST';
export const ENTITY_FETCH_SUCCESS = 'ENTITY_FETCH_SUCCESS';

export const ENTITY_PATCH_ABANDON = 'ENTITY_PATCH_ABANDON';
export const ENTITY_PATCH_FAILURE = 'ENTITY_PATCH_FAILURE';
export const ENTITY_PATCH_REQUEST = 'ENTITY_PATCH_REQUEST';
export const ENTITY_PATCH_SUCCESS = 'ENTITY_PATCH_SUCCESS';

export const ENTITY_STORE_ABANDON = 'ENTITY_STORE_ABANDON';
export const ENTITY_STORE_FAILURE = 'ENTITY_STORE_FAILURE';
export const ENTITY_STORE_REQUEST = 'ENTITY_STORE_REQUEST';
export const ENTITY_STORE_SUCCESS = 'ENTITY_STORE_SUCCESS';

export const ENTITY_WASTE_ABANDON = 'ENTITY_WASTE_ABANDON';
export const ENTITY_WASTE_FAILURE = 'ENTITY_WASTE_FAILURE';
export const ENTITY_WASTE_REQUEST = 'ENTITY_WASTE_REQUEST';
export const ENTITY_WASTE_SUCCESS = 'ENTITY_WASTE_SUCCESS';

export const CLOSE_SAVE_ABANDON = 'CLOSE_SAVE_ABANDON';
export const CLOSE_SAVE_FAILURE = 'CLOSE_SAVE_FAILURE';
export const CLOSE_SAVE_REQUEST = 'CLOSE_SAVE_REQUEST';
export const CLOSE_SAVE_SUCCESS = 'CLOSE_SAVE_SUCCESS';

export const START_LOAD_ABANDON = 'START_LOAD_ABANDON';
export const START_LOAD_FAILURE = 'START_LOAD_FAILURE';
export const START_LOAD_REQUEST = 'START_LOAD_REQUEST';
export const START_LOAD_SUCCESS = 'START_LOAD_SUCCESS';

export const SIGN_IN_ABANDON = 'SIGN_IN_ABANDON';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_OUT_ABANDON = 'SIGN_IN_ABANDON';
export const SIGN_OUT_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_UP_ABANDON = 'SIGN_IN_ABANDON';
export const SIGN_UP_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_UP_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_IN_SUCCESS';

export const TASK_ASYNC_ABANDON = 'TASK_ASYNC_ABANDON';
export const TASK_ASYNC_FAILURE = 'TASK_ASYNC_FAILURE';
export const TASK_ASYNC_REQUEST = 'TASK_ASYNC_REQUEST';
export const TASK_ASYNC_SUCCESS = 'TASK_ASYNC_SUCCESS';

export const TASK_AWAIT_ABANDON = 'TASK_AWAIT_ABANDON';
export const TASK_AWAIT_FAILURE = 'TASK_AWAIT_FAILURE';
export const TASK_AWAIT_REQUEST = 'TASK_AWAIT_REQUEST';
export const TASK_AWAIT_SUCCESS = 'TASK_AWAIT_SUCCESS';

export * from './change/types';
export * from './operations/types';